### PR TITLE
Added ags overview widget

### PR DESCRIPTION
**Pull request by SherLock707**
Added overview widget which makes it easy to move lot of window around work-spaces.
## Features
1. Drag any open window and drop in any workspace
2. Search and open any app

## Description

This is a stripped down and pywal integrated (+ other misc improvement) version of original widget from [here](https://github.com/end-4/dots-hyprland).

Added `MOD+a` to trigger overview launch (run `ags &` if not running in background already )

To update scale and number of rows, adjust values at `~./config/ags/user_options.js`

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ?] My change requires a change to the documentation.
- [ ?] I want to add something in Hyprland-Dots wiki.
- [x ] I have added tests to cover my changes.
- [ x] I have tested my code locally and it works as expected.
- [ x] All new and existing tests passed.

## Screenshots

Screenshot_2024-04-24-22-21-17_27952

OVERVIEW_full

## Additional context

Needs ' aylurs-gtk-shell' package. I'm running 'aylurs-gtk-shell 1.8.0-1' as of this MR.

Installation for different distros:[https://aylur.github.io/ags-docs/config/installation/]( https://aylur.github.io/ags-docs/config/installation/)

### For testing.
1. Move ags directory into ~/.config/
3. Open terminal ` ags &`
4. Run ` ags -t 'overview'`

@JaKooLit I use ultrawide monitor and this works fine for me, please try and let me know if any issue due to monitor size. (Although `~/.config/ags/variables.js`  should get user screen size)

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Just upvoting it :) It would be a nice addition!

**Comment by JaKooLit** [comment]
is ags stable enough? because if so, would drop waybar too in favor of ags

**Comment by SherLock707** [comment]
> is ags stable enough? because if so, would drop waybar too in favor of ags

Its stable from my experience so far, I've been using it for past few weeks, had no issues.
Its well documented too.
But porting everything from Waybar to ags based bar would be lot of work I feel 😂.
Above original repo has bar and other stuff implemented, didn't try it though.

**Comment by JaKooLit** [comment]
putting this on hold for now :)

Once Ive got time, will move to ags..

although not anytime soon though :)

As always, thanks alot

**Comment by JohnRTitor** [comment]
Tried this. Looks beautiful.

image

But what is this UI bug "travel_explore" "settings_b_roll"?

image


image

**Comment by SherLock707** [comment]
> ## Tried this. Looks beautiful.
> image
> image
> 
> 
> ## But what is this UI bug "travel_explore" "settings_b_roll"?
> 
> image
> 
> 
> image
> 

Awesome! 
I didn't get time to look into that search function well (had considered removing at one point). Will look into it tomorrow and post here.

**Comment by SherLock707** [comment]
@JohnRTitor , I updated things you mentioned above, should look  better now.

**Comment by SherLock707** [comment]
Do you think the search UI needs Pywal integration or it looks fine?

**Comment by JohnRTitor** [comment]
> Do you think the search UI needs Pywal integration or it looks fine?

Definitely needs Pywal integration.

image

The bugs seem to have been fixed.

**Comment by SherLock707** [comment]
Not sure how this will work for white mode.

image


image

**Comment by SherLock707** [comment]
I never squashed commits before, how do I do that?

**Comment by JohnRTitor** [comment]
First you need to integrate your changes to upstream/development repository like:
```bash
git fetch upstream
git rebase upstream/development
```
This will rebase your changes on top of the current development branch. But don't push yet.
```bash
git rebase --interactive HEAD~6
```
HEAD~6 is how far you want to go back rebase, since you have 6 commits in total, you can use `HEAD~6`.

You'll see something like `pick i6xhen "Commit message"` line by lines. Change the last 5 commits `pick` to `squash`, then save. This will squash the last 5 commits into your first commit in the chain. It'll open up another text editor window for you to edit the final message. Saving it should complete the process.

Then force push to your forked branch using
```bash
git push --force-with-lease
```

**Comment by SherLock707** [comment]
> ```shell
> git rebase --interactive HEAD~6
> ```

I had tried this when I looked up online, but I get this message after above rebase:
image

**Comment by JohnRTitor** [comment]
Please change the default editor to nano in your gitconfig.

**Comment by SherLock707** [comment]
Done I guess? I don't see any effect in commit history

image

**Comment by JohnRTitor** [comment]
Did you change `pick` to `squash`?

**Comment by SherLock707** [comment]
Yes, in nvim, saved and quit with this :
image

**Comment by JaKooLit** [comment]
I feel like I need to close this and make another branch for ags? 

what do you think guys? I need to also do test here so I can integrate on all the distros

**Comment by JohnRTitor** [comment]
> Yes, in nvim, saved and quit with this : image


Lmao you definitely did not do what I asked. 
`pick` should be changed to `squash` for cb2dc23 and below commits.

**Comment by SherLock707** [comment]
> I feel like I need to close this and make another branch for ags?
> 
> what do you think guys? I need to also do test here so I can integrate on all the distros

Yes, I think we can keep it in new branch and test.

**Comment by SherLock707** [comment]
> I feel like I need to close this and make another branch for ags?
> 
> what do you think guys? I need to also do test here so I can integrate on all the distros

Also, the way this ags is added in config is static as it does not use the scss compilation, which is done in original repo: [https://github.com/end-4/dots-hyprland](https://github.com/end-4/dots-hyprland) . And I think original repo's way of installation would be better for mutiple distro.

**Comment by JaKooLit** [comment]
Ok Im closing this PR...

Kindly push to experimental-ags branch

https://github.com/JaKooLit/Hyprland-Dots/tree/experimental-ags

**Pull request closed without merging**
