### PR TITLE
Update ModulesCustom

### PR DESCRIPTION
**Pull request by squassina**
simplify custom/updater on-click command.

# Pull Request

## Description

Please read these instructions and remove unnecessary text.

Adjust on-click command to custom/updater, by simplifying the latest update

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [X] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [X] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [X] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [ ] I have added tests to cover my changes.
- [X] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Additional context

Original version was resulting in and error and the new version is too complicated. I simplified the command to run without any error and making it more readable.

### CODE REVIEW

**Comment by JaKooLit** [comment]
you cant do that because:
first: you need an alias 
update to aur(paru or yay) -Syu

or if using oh my zsh with archlinux plugin, you need upgrade instead

with the old command, it will work without doing any changes

**Comment by squassina** [comment]
Hum, I didn't understand. I tried this command using your scripts with only this line changed, did you tried it? 

here's my system infos:

Linux 6.1.75-rockchip-g2a5e23f029ac-dirty (I'm on aarch64)
Hyprland (Wayland)
zsh 5.9
kitty 0.36.4

**Comment by squassina** [comment]
I just wrote the command using eval, can you check it now on you end, please? Thanks!

**Comment by JaKooLit** [comment]
https://github.com/Morganamilo/paru

actually paru works same as yay

by typing only yay or paru 

both commands will update system

however, the original code will check first of yay is installed and will execute yay -Syu and so as paru.

your original MR works as well (should be)

I dont know about eval

unfortunately, I cannot test it myself since I have a very limited data

but do you have any issues with the original code?

**Comment by squassina** [comment]
not at all! I was having with the very original one, when it was in  `modules`  only file. Then I re-write with this one. After that I noticed that you have changed to a much better files organization and the command has changed.

I just found it was simpler to maintain then an in-line `if` syntax.

I'm fine with both.

**Pull request closed without merging**
