### PR TITLE
Close Rofi if running when ags overview is launched

### PR DESCRIPTION
**Pull request by SherLock707**
# Pull Request

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ x] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [ ] I have added tests to cover my changes.
- [ x] I have tested my code locally and it works as expected.
- [ x] All new and existing tests passed.

## Additional context

@JohnRTitor 's suggestion :)

### CODE REVIEW

**Comment by SherLock707** [comment]
> And vice versa :) ags should be closed before running rofi :)
> 
> Only one should be kept on the screen at a time.

Might be bit tricky since killing whole ags is hacky way and another way would be to store the toggle state returned by `ags -t 'overview'`

**Comment by JaKooLit** [comment]
> > And vice versa :) ags should be closed before running rofi :)
> > Only one should be kept on the screen at a time.
> 
> Might be bit tricky since killing whole ags is hacky way and another way would be to store the toggle state returned by `ags -t 'overview'`
> 
> I have to do something like `bind = $mainMod, A, exec, pkill rofi || true && $OVERVIEW_STATE=ags -t 'overview'`
> 
> `bindr = $mainMod, $mainMod_L, exec, $OVERVIEW_STATE -eq "true" && ags -t 'overview' || true && pkill rofi || rofi -show drun -modi drun,filebrowser,run,window`
> 
> Got a better way?

One suggestion 
for overview - Super O
For Super Shift D

**Comment by SherLock707** [comment]
> > > And vice versa :) ags should be closed before running rofi :)
> > > Only one should be kept on the screen at a time.
> > 
> > 
> > Might be bit tricky since killing whole ags is hacky way and another way would be to store the toggle state returned by `ags -t 'overview'`
> > I have to do something like `bind = $mainMod, A, exec, pkill rofi || true && $OVERVIEW_STATE=ags -t 'overview'`
> > `bindr = $mainMod, $mainMod_L, exec, $OVERVIEW_STATE -eq "true" && ags -t 'overview' || true && pkill rofi || rofi -show drun -modi drun,filebrowser,run,window`
> > Got a better way?
> 
> One suggestion for overview - Super O For Super Shift D

Wouldn't 'O' be too far for quick access?
Super shift D for ?

**Comment by JaKooLit** [comment]
> > > > And vice versa :) ags should be closed before running rofi :)
> > > > Only one should be kept on the screen at a time.
> > > 
> > > 
> > > Might be bit tricky since killing whole ags is hacky way and another way would be to store the toggle state returned by `ags -t 'overview'`
> > > I have to do something like `bind = $mainMod, A, exec, pkill rofi || true && $OVERVIEW_STATE=ags -t 'overview'`
> > > `bindr = $mainMod, $mainMod_L, exec, $OVERVIEW_STATE -eq "true" && ags -t 'overview' || true && pkill rofi || rofi -show drun -modi drun,filebrowser,run,window`
> > > Got a better way?
> > 
> > 
> > One suggestion for overview - Super O For Super Shift D
> 
> Wouldn't 'O' be too far for quick access? Super shift D for ?

launch menu?

**Pull request merged**
