### PR TITLE
Added ags overview widget

### PR DESCRIPTION
**Pull request by SherLock707**
Added overview widget which makes it easy to move lot of window around work-spaces.
## Features
1. Drag any open window and drop in any workspace
2. Search and open any app

## Description

This is a stripped down and pywal integrated (+ other misc improvement) version of original widget from [here](https://github.com/end-4/dots-hyprland).

Added `MOD+a` to trigger overview launch (run `ags &` if not running in background already )

To update scale and number of rows, adjust values at `~./config/ags/user_options.js`

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ?] My change requires a change to the documentation.
- [ ?] I want to add something in Hyprland-Dots wiki.
- [x ] I have added tests to cover my changes.
- [ x] I have tested my code locally and it works as expected.
- [ x] All new and existing tests passed.

## Screenshots

Screenshot_2024-04-24-22-21-17_27952

OVERVIEW_full

## Additional context

Needs ' aylurs-gtk-shell' package. I'm running 'aylurs-gtk-shell 1.8.0-1' as of this MR.

Installation for different distros:[https://aylur.github.io/ags-docs/config/installation/]( https://aylur.github.io/ags-docs/config/installation/)

### For testing.
1. Move ags directory into ~/.config/
3. Open terminal ` ags &`
4. Run ` ags -t 'overview'`

@JaKooLit I use ultrawide monitor and this works fine for me, please try and let me know if any issue due to monitor size. (Although `~/.config/ags/variables.js`  should get user screen size) 

Copied from #215

### CODE REVIEW

**Comment by JaKooLit** [comment]
thanks... so just need to install ags?

**Comment by SherLock707** [comment]
> thanks... so just need to install ags?

Yes.

image

**Comment by JaKooLit** [comment]
cool.. I will just finalized what Im doing now and then will test this on the new Arch Ive installed last night on a separate partition

**Comment by JohnRTitor** [comment]
## Tested it in light mode
 
image

image

**Comment by SherLock707** [comment]
> ## Tested it in light mode

Should this be light colour?
image

**Comment by JohnRTitor** [comment]
Yes, and the text should be dark/black in light mode.

**Comment by SherLock707** [comment]
> Yes, and the text should be dark/black in light mode.

can you share the content of `~/.cache/wal/colors-waybar.css` with above wallpaper please?

**Comment by JaKooLit** [comment]
> ## Tested it in light mode
>  
> image
> 
> image
> 

oh... seems like with this I can drop the rofi menu 🤣

**Comment by JaKooLit** [comment]
https://discord.com/channels/1151869464405606400/1236220998903402556

faster and easier to discuss here

@SherLock707  youre on my DC right? I forgot your username tbh 😁 sorry

**Comment by SherLock707** [comment]
> https://discord.com/channels/1151869464405606400/1236220998903402556
> 
> faster and easier to discuss here
> 
> @SherLock707 youre on my DC right? I forgot your username tbh 😁 sorry

Yes I'm, but I rarely open discord. I'll try to get on it later when I have more time.

**Pull request merged**
