### PR TITLE
Change flow of the wallpapers to horizontal

### PR DESCRIPTION
**Pull request by m0r4a**
This change ensures that when searching for a wallpaper and there aren't enough options to fill all the columns and rows, it prioritizes filling the rows instead of the columns.

# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ ] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [ ] I have added tests to cover my changes.
- [ ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by dwilliam62** [comment]
Thank you for the submission.   This does seem to work better.   Especially with the scroll wheel.   In the future if you could add more info about your suggested change we would appreciate it.   I will recommend the he add this in.   He is out of the country at the moment, so he will review this as soon as he can.

**Comment by m0r4a** [comment]
Hi, I'm sorry. I didn't realize that I actually submitted the pull request. I will close it and make a feature request instead. Sorry for the inconvenience.

**Comment by dwilliam62** [comment]
Ok you didn't have to close it.  just looking for more info when you submit things.   In this case it was an easy add.  I am using it at the moment in fact.

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/c3900285bcb30a5af49c638eb3c16bd43e2c2527

**Pull request closed without merging**
