### PR TITLE
Development

### PR DESCRIPTION
**Pull request by 0xl30**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [x ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ x] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x ] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [ ] I have added tests to cover my changes.
- [x ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots
swappy-20241020-222612
swappy-20241020-222651
swappy-20241020-222628

(if appropriate)

## Additional context
when github repo change version(update code get pop-up show and skip if click show fetch version.html(github) in user machine(check what feature add change and others change)
Need Some Change Code (Add Your Github Profile,KeyHints,Version Style etc etc)
version.html css added problems(hope fixed)

### CODE REVIEW

**Comment by JaKooLit** [comment]
thanks for this and looks good.

However, ill try myself first once Ive got home. I just dont have time right now.

Next month ill look into it

**Comment by 0xl30** [comment]
Ok,Yad so interesting i playing with yad then make this like a updater apps but problem is .sh script can't direct execute,first need set defualt open app is kitty terminal,swappy-20241023-194335 i expect you can make this perfect

**Comment by JaKooLit** [comment]
yeah shouldnt be an issue. 

as ive said, Ill look into it cause I can already tell needs a fine tuning so it will be compatible across distros

I may introduce to debian / and ubuntu as well or atleast I will try

**Comment by JaKooLit** [comment]
danggit.. it automatically closed lmao

**Pull request merged**
