### PR TITLE
Weather Source Update (Python File)

### PR DESCRIPTION
**Pull request by 0xl30**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [ x] **Bug fix** (non-breaking change which fixes an issue)
- [ x] **New feature** (non-breaking change which adds functionality)
- [x ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [x ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ x] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ x] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [x ] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [x ] My change requires a change to the documentation.
- [x ] I want to add something in Hyprland-Dots wiki.
- [ x] I have added tests to cover my changes.
- [x ] I have tested my code locally and it works as expected.
- [x ] All new and existing tests passed.

## Screenshots
swappy-20240204-202313
 
On Mouse 
swappy-20240204-202530

## Additional context
Work On City Based,No Sever Issue,If User Use VPN Don't Change Output(1st Time Need User Enter Manually City Data. All Details Inside Code)

### CODE REVIEW

**Comment by JohnRTitor** [comment]
I am testing it is my fork. 
Would be nice if the popup could be more transclusent. Overall I'm all for the improvement.

**Comment by JaKooLit** [comment]
sorry took long time for me to review this. It looks good, however, how to set a city of choice? a Major city for example.

**Comment by JohnRTitor** [comment]
Here's what I did. Went to weather.com, searched my city, went to my city's weather page.
URL should be like: https://weather.com/en-US/weather/today/l/<hash>

Copy the hash and add to the script.

For example, the [weather for San Paolo](https://weather.com/en-IN/weather/today/l/24ad1305205b675a4165b13e3638cf90b620c87a7e234c1a7365d6b67aaadb12) has the hash `24ad1305205b675a4165b13e3638cf90b620c87a7e234c1a7365d6b67aaadb12`

**Comment by JaKooLit** [comment]
oh its on the file lmao

thanks. let me have a quick review theb

**Comment by JaKooLit** [comment]
hmmmm.. needs pyquery... Ill put on hold on this as definitely will break for other distros. Need to test once im home..

but I will keep this open for now

**Review by JaKooLit — APPROVED** [review]

**Pull request merged**
