### PR TITLE
Added Waypaper as wallpaper switcher if you have it installed

### PR DESCRIPTION
**Pull request by SherLock707**
# Pull Request

## Description
Waypaper is faster to launch if you have lot of images in wallpaper folder.

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x ] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [x ] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [x ] I have added tests to cover my changes.
- [x ] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

image

## Additional context

[https://github.com/anufrievroman/waypaper](https://github.com/anufrievroman/waypaper)
(Dev is super friendly)

image

### CODE REVIEW

**Comment by JaKooLit** [comment]
waypaper have search function?

How many wallpapers do you have?

**Comment by JaKooLit** [comment]
tried it... Im more on not like it side :)

Installing via python is a hit and miss in most distros

**Comment by SherLock707** [comment]
> waypaper have search function?
> 
> How many wallpapers do you have?

No it does not have search.

I have ~100 wallpapers.. I can see a delayed (1-2 sec) loading of 'thumbnail' in rofi-based wallpaper selector.

**Comment by SherLock707** [comment]
> tried it... Im more on not like it side :)
> 
> Installing via python is a hit and miss in most distros

oh, yeah. I want to have rofi for everything possible, but wallpaper selector with rofi felt bit hacky..

**Comment by JaKooLit** [comment]
I have tried on my system with almost 900 wallpapers

no issue. no delay..

the delay on waypaper was the caching part

**Comment by JaKooLit** [comment]
with current config with rofi,

I edited the path to my big wallpaper  directory, 886 wallpapers, 1.5gb size

launch the rofi-wallpaper quick search.. no delay

rendering also no issue

**Comment by SherLock707** [comment]
> with current config with rofi,
> 
> I edited the path to my big wallpaper directory, 886 wallpapers, 1.5gb size
> 
> launch the rofi-wallpaper quick search.. no delay
> 
> rendering also no issue

Oh okay cool, I'll check my config then.

**Comment by SherLock707** [comment]
> > > with current config with rofi,
> > > I edited the path to my big wallpaper directory, 886 wallpapers, 1.5gb size
> > > launch the rofi-wallpaper quick search.. no delay
> > > rendering also no issue
> > 
> > 
> > Oh okay cool, I'll check my config then.
> 
> by the way, make sure you have rofi-wayland and not the rofi only
> 
> else you will have issues.. rofi will work but some things are not compatible with rofi.

Yup, have the `rofi-lbonn-wayland-git`


Other then 1-2 second load delay no other issue. I thinks its due to my up-scaled ultra-wide wallpaper size

**Comment by JaKooLit** [comment]
rofi wayland is already on official repo

no need for the git version

can you attach a video about that delay?

**Comment by SherLock707** [comment]
> rofi wayland is already on official repo
> 
> no need for the git version
> 
> can you attach a video about that delay?

Cool, I'm using older version of your dots. I'll figure out, thanks

**Comment by JaKooLit** [comment]
> > rofi wayland is already on official repo
> > no need for the git version
> > can you attach a video about that delay?
> 
> Cool, I'm using older version of your dots. I'll figure out, thanks

ok.. so I can close this?

**Pull request closed without merging**
