### PR TITLE
Replaced dunst with swaync

### PR DESCRIPTION
**Pull request by SherLock707**
## Replaced Dunst with [Swaync](https://github.com/ErikReider/SwayNotificationCenter) for a notification centre UI.

1. Volume and brightness notification works as expected.
2. Added Key bind SUPER+N to open notification center
3. Added basic support for pywall from pywall waybar css

Tested and using on my system:

image

image

## Additional Notes

- Installation of swaync package is not part of this PR
- Theme needs polish
- Need to test on other monitor resolution (Mine is 3440x1440)
- More functionality and buttons can be implemented in Notification centre

### CODE REVIEW

**Comment by JaKooLit** [comment]
Please merge in other branch so I can test first

There is a development branch

Thanks...

although, one question, swaync can handle the volume and brightness control without putting them in history?

**Comment by SherLock707** [comment]
> Please merge in other branch so I can test first
> 
> There is a development branch
> 
> Thanks...
> 
> although, one question, swaync can handle the volume and brightness control without putting them in history?

I ran:
> git merge upstream/development
Already up to date.

Please let me know if I'm following the correct method.

**Comment by SherLock707** [comment]
Also added waybar module for swaync

**Comment by JaKooLit** [comment]
yeah thats why its better to push on development so I can test first.. so I can adjust with distro-hyprland install script as well...

However, you should push in your development branch first and push in my development branch....

I will close this first

**Comment by SherLock707** [comment]
> although, one question, swaync can handle the volume and brightness control without putting them in history?

Yes if you use notify-send -e it does not add it to history in panel.
`-e, --transient                   Create a transient notification`

**Comment by JaKooLit** [comment]
> > although, one question, swaync can handle the volume and brightness control without putting them in history?
> 
> Yes if you use notify-send -e it does not add it to history in panel. `-e, --transient Create a transient notification`

excellent... I have actually a "standby" swaync config :)

But lets make the main clean

**Comment by SherLock707** [comment]
Thanks, I merged my branch with dev of fork, should I now use that dev branch to open PR with your dev branch?

**Comment by Ja-KooLit** [comment]
Hi this is my other acct... 

I think I found now a way...

I suggest to do the following

swappy-20231226-191409

Kindly refork to copy the development branch

and then you work on your development branch

and then once ready, push from your development

swappy-20231226-191122

**Pull request closed without merging**
