### PR TITLE
Added notification tone for swaync notification

### PR DESCRIPTION
**Pull request by SherLock707**
# Added notification tone for swaync notification

- Plays notification tone when you receive a notification
- Would not play tone when volume, brightness change notification is received.

## Type of change

Please put an `x` in the boxes that apply:

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ x] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [ ] I have added tests to cover my changes.
- [ x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

## Additional context

Volume of notification is set to 50%.
More tone can be added by manual method.

### CODE REVIEW

**Comment by SherLock707** [comment]
The play command uses sox package from arch Extra repo:

[sox](https://sourceforge.net/projects/sox/) : The Swiss Army knife of sound processing tools

**Comment by SherLock707** [comment]
I guess I missed v2.2.2 release window 😅

**Comment by JaKooLit** [comment]
Its fine. Will just collect again improvements for next release :)

Just a question about the sound notification... will this not conflict with apps notification sounds?

**Comment by SherLock707** [comment]
If any app produces its own notification sound, we can include name of that app here in regex to not play sound for that..
`"app-name": "^(?!.*\\b(volume|brightness)\\b).*"`

or we can update regex to play sound for only certain notification..

**Comment by JaKooLit** [comment]
yeah and thats an issue cause there are alot out there who are used to have their own sound or they are used to the apps sound... 

And by the way, I have tried, Im getting some error....

any dependencies needed?

**Comment by SherLock707** [comment]
only `sox` package to get `play` utility.

We can check if is there any preinstalled utils that can play sound via cli.

**Comment by JaKooLit** [comment]
sorry, swaync dont officially support... yet

https://github.com/ErikReider/SwayNotificationCenter/issues/58

**Pull request closed without merging**
