### PR TITLE
Swapped out xrandr to hyprctl monitors in ags overview

### PR DESCRIPTION
**Pull request by SherLock707**
## Type of change

Please put an `x` in the boxes that apply:

- [x ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [ ] I have added tests to cover my changes.
- [ x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by JaKooLit** [comment]
https://raw.githubusercontent.com/JaKooLit/Telegram-Animated-Emojis/main/People/Clapping%20Hands.webp https://raw.githubusercontent.com/JaKooLit/Telegram-Animated-Emojis/main/People/Clapping%20Hands.webp https://raw.githubusercontent.com/JaKooLit/Telegram-Animated-Emojis/main/People/Clapping%20Hands.webp https://raw.githubusercontent.com/JaKooLit/Telegram-Animated-Emojis/main/People/Clapping%20Hands.webp https://raw.githubusercontent.com/JaKooLit/Telegram-Animated-Emojis/main/People/Clapping%20Hands.webp

**Comment by JohnRTitor** [comment]
Nice

**Comment by SherLock707** [comment]
> Great job.. it actually feels snappier now than using xrandr

Awesome! I though of getting rid of it earlier, but totally forgot about `hyprctl monitors`

**Comment by JaKooLit** [comment]
Sparkles 
Sparkles 
Sparkles

**Comment by SherLock707** [comment]
Don't have multi-monitor setup, but we could also make this adapt to any monitor size if we can get active/focused monitor id.

**Comment by JaKooLit** [comment]
> > Great job.. it actually feels snappier now than using xrandr
> 
> Awesome! I though of getting rid of it earlier, but totally forgot about `hyprctl monitors`

I was actually to forced to go through ags configs earlier after reformatting my Gentoo.... and I noticed about xrandr...

and a simple installing xrandr fixed the issue... my fault.. should have thought of it sooner

**Comment by JaKooLit** [comment]
> Don't have multi-monitor setup, but we could also make this adapt to any monitor size if we can get active/focused monitor id.

its what I used before on the wallpaper scripts

**Comment by SherLock707** [comment]
> > Great job.. it actually feels snappier now than using xrandr
> 
> Awesome! I though of getting rid of it earlier, but totally forgot about `hyprctl monitors`

I can get active workspace's monitor id using `hyprctl activeworkspace` and use it to get that monitor's dimension. But have to refresh it each time overview is launched, might affect launch-latency I guess.. need to test it out..
Of course need someone with muti-monitor (different resolutions) setup to test it..

**Comment by SherLock707** [comment]
> > > > Great job.. it actually feels snappier now than using xrandr
> > > 
> > > 
> > > Awesome! I though of getting rid of it earlier, but totally forgot about `hyprctl monitors`
> > 
> > 
> > I can get active workspace's monitor id using `hyprctl activeworkspace` and use it to get that monitor's dimension. But have to refresh it each time overview is launched, might affect launch-latency I guess.. need to test it out.. Of course need someone with muti-monitor (different resolutions) setup to test it..
> 
> nah I actually felt the the latency right away after switching to hyprctl monitors
> 
> I have tried changing scaling on my other monitor to see if affects.. but it looks fine.. it seems abit small now though but its ok... I like it better..
> 
> you have the ultra wide version right?

Yup, 3440x1440

**Comment by JaKooLit** [comment]
yup I know.... but I will try later on... thanks alot bro

**Comment by JaKooLit** [comment]
oh its back to before 😁

**Pull request merged**
