### PR TITLE
Hyprlock weather delay fix

### PR DESCRIPTION
**Pull request by SherLock707**
# Pull Request

## Type of change

Please put an `x` in the boxes that apply:

- [ x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [ x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [ x] My code follows the code style of this project.
- [ x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [x ] I have added tests to cover my changes.
- [ x] I have tested my code locally and it works as expected.
- [ x] All new and existing tests passed.

## Screenshots
Shell Script version:
Screenshot_2024-05-06-22-06-02_17534

Python script version:
Screenshot_2024-05-06-22-06-32_23574

### CODE REVIEW

**Comment by JaKooLit** [comment]
awesome

**Comment by JohnRTitor** [comment]
Can you implement something like this with the Python script (Weather.py) too?

**Comment by JaKooLit** [comment]
he did

**Comment by SherLock707** [comment]
> Can you implement something like this with the Python script (Weather.py) too? 

Its for both shell script and python script..

**Pull request merged**
