### PR TITLE
fix dpms action

### PR DESCRIPTION
**Pull request by tonyho**
# Pull Request

## Description

Please read these instructions and remove unnecessary text.

- Try to include a summary of the changes and which issue is fixed.
- Also include relevant motivation and context (if applicable).
- List any dependencies that are required for this change. (e.g., packages or other PRs)
- Provide a link if there is an issue related to this pull request. e.g., Fixes # (issue)
- Please add Reviewers, Assignees, Labels, Projects, and Milestones to the PR. (if applicable)

## Type of change

Please put an `x` in the boxes that apply:

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] **Documentation update** (non-breaking change; modified files are limited to the documentations)
- [ ] **Technical debt** (a code change that does not fix a bug or add a feature but makes something clearer for devs)
- [ ] **Other** (provide details below)

## Checklist

Please put an `x` in the boxes that apply:

- [x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Hyprland-Dots/blob/main/CONTRIBUTING.md#git-commit-messages).
- [ ] My change requires a change to the documentation.
- [ ] I want to add something in Hyprland-Dots wiki.
- [ ] I have added tests to cover my changes.
- [x] I have tested my code locally and it works as expected.
- [ ] All new and existing tests passed.

## Screenshots

(if appropriate)

### CODE REVIEW

**Comment by JaKooLit** [comment]
kindly complete all thw information needed

**Comment by ThaSiouL** [comment]
wait why do you want to turn the monitor off after waking up from sleep?

**Comment by tonyho** [comment]
> kindly complete all thw information needed↳

Now I fullfill the infomation. But the commit messge format, I thinks it can be changed when merging.

**Comment by JaKooLit** [comment]
> > kindly complete all thw information needed↳
> 
> Now I fullfill the infomation. But the commit messge format, I thinks it can be changed when merging.

https://github.com/JaKooLit/Hyprland-Dots/pull/341#issuecomment-2168075650

pls answer his question

**Comment by tonyho** [comment]
> Wait why do you want to turn the monitor off after waking up from sleep? Have you tested this?↳

Yes, I tested it locally. 

Plus, for the on/off on ' hyprctl dispatch dpms on ', I tested directly on terminal
hyprctl dispatch dpms off: will  turn off all my monitors

**Comment by ThaSiouL** [comment]
But why do you want to turn off the monitor _after_ waking the PC up from sleep?
What's the use case for that?

**Comment by JaKooLit** [comment]
Since you didnt answer @ThaSiouL question, I am squashing this PR

**Pull request closed without merging**
