### PR TITLE
Patch-RofiBeats

### PR DESCRIPTION
**Pull request by Linxford**
# Pull Request

## Description
Implemented functionality to play all songs in either order or shuffled from the local music folder..

### CODE REVIEW

**Comment by JohnRTitor** [comment]
Go to "Edit", and change the base branch to `development`. Thanks!

**Comment by JohnRTitor** [comment]
Since you seem to have cloned the main branch. You need to fix this.

In your cloned repo:
Run `git fetch upstream`
Run `git rebase upstream/development`
And then `git push --force-with-lease` to force push the changes.

**Comment by JaKooLit** [comment]
the play in order is working but now the shuffle

and btw, to avoid conflict, kindly rebase your fork before before pushing a PR..

this is to avoid conflicts like this patch now


So I am closing this for now....

rebase your fork and then edit according.

just a small note, I have create a Rofi-Beats menu rofi config. Kindly integrate that as it will look better

**Comment by JaKooLit** [comment]
I dont see the patch 😄

**Pull request closed without merging**
